repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: tb-fmt
        name: tb fmt
        entry: tb fmt --yes --line-length 100
        language: system
        files: '\.(incl|pipe|datasource)$'
